
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "account" : "staff2",
  "password" : "kkkkkk"
}
### 
POST http://localhost:5000/api/auth/login
Content-Type:  application/json

{
  "account": "staff1",
  "password": "kkkkkk"
}
###
POST http://localhost:5000/api/customer
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

{
  "name": " Xuân Trường6",
  "email": "truong@gmail.com",
  "img": "https://static-images.vnncdn.net/files/publish/2022/9/3/bien-vo-cuc-thai-binh-346.jpeg",
  "telephoneNumber": "0987236487",
  "address": "Sài Gòn"
}
###
PUT http://localhost:5000/api/customer/645723267ca07cc1fa0d6e1d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

{
  "name": "khachhang123",
  "email": "email",
  "img": "img",
  "telephoneNumber": "123",
  "address": "address"
}
###
GET http://localhost:5000/api/customer/GetAllCustomer
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

