
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "account" : "staff5",
  "password" : "kkkkkk",
  "fullname" : "truiongvip",
  "address": "Sai gon",
  "sex": "Nam",
  "birthDay": "01/11",
  "email" : "truong@gmail.com",
  "telephoneNumber": "0987980987",
  "avatarUrl": "https://vn.blog.kkday.com/wp-content/uploads/chup-anh-dep-bang-dien-thoai-25.jpg"
}
### 
POST http://localhost:5000/api/auth/login
Content-Type:  application/json

{
  "account": "staff1",
  "password": "kkkkkk"
}
###
GET  http://localhost:5000/api/auth/getAllStaffs
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

{
  "account": "staff1",
  "password": "kkkkkk"
}
###
PUT  http://localhost:5000/api/auth/update/64630f7e68c4ec656abd1956
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

{
  "fullname": "truong",
  "address": "Sai gon",
  "sex": "male", 
  "birthDay": "birday", 
  "email": "email",
  "telephoneNumber": "telephone",
  "avatarUrl": "avaurl"
}
###
DELETE  http://localhost:5000/api/auth/delete/64630f8268c4ec656abd1959
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

###
GET  http://localhost:5000/api/auth/search/012
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

###
POST http://localhost:5000/api/customer
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

{
  "name": " Xuân Trường6",
  "email": "truong@gmail.com",
  "img": "https://static-images.vnncdn.net/files/publish/2022/9/3/bien-vo-cuc-thai-binh-346.jpeg",
  "telephoneNumber": "0987236487",
  "address": "Sài Gòn"
}
###
PUT http://localhost:5000/api/customer/645723267ca07cc1fa0d6e1d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

{
  "name": "khachhang123",
  "email": "email",
  "img": "img",
  "telephoneNumber": "123",
  "address": "address"
}
###
GET http://localhost:5000/api/customer/GetAllCustomer
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3MTljYzg2NjAyMTY2MDU5MjgzOGQiLCJpYXQiOjE2ODM0MzIxODh9.0pH2sC8WHRyJuJwEiCR5Hhu0RGhkF63eh9GRkA0UJzg

